(define (iterfast-expt b n)
  (define (iter a b n)
    (cond ((= n 0) 1)
          ((= n 1) a)
          ((even? n) (iter (* a (square b)) b (/ n 2)))
          (else (iter (* a b) b (- n 1)))))
  (iter 1 b n))
