(define (fast-* b n)
  (define (double x)
    (+ x x))
  (define (halve x)
    (/ x 2))
  (define (rec b n)
    (cond ((= n 0) 0)
          ((= n 1) b)
          ((= n 2) (double b))
          ((even? n) (+ (double b) (rec b (halve n))))
          (else (+ b (rec b (-  n 1))))))
  (rec b n))
