(define (iterfast-* b n)
  (define (double x)
    (+ x x))
  (define (halve x)
    (/ x 2))
  (define (iter a b n)
    (cond ((= n 0) 0)
          ((= n 1) a)
          ((even? n) (iter (+ a (double b)) b (halve n)))
          (else (iter (+ a b) b (- n 1)))))
  (iter 0 b n))
